backports/collectd: backport amove() function

diff --git a/backports/collectd/APKBUILD b/backports/collectd/APKBUILD
--- a/backports/collectd/APKBUILD
+++ b/backports/collectd/APKBUILD
@@ -204,6 +204,28 @@ _plugin() {
 	done
 }
 
+# XXX: Ported from abuild 3.5.0_rc2
+amove() {
+	# store directory
+	local d="$(pwd -L)"
+
+	cd "$pkgdir"
+	local pattern f
+	for pattern; do
+		for f in ${pattern#/}; do # let shell expand the pattern
+			# only create dir if needed
+			if [ "${f%/*}" != "$f" ]; then
+				mkdir -p "$subpkgdir/${f%/*}"
+			fi
+			mv -v "$pkgdir"/$f "$subpkgdir/${f%/*}"
+			# cleanup
+			rmdir -p "$f" || rmdir -p "${f%/*}" || true
+		done
+	done
+
+	cd "$d"
+}
+
 sha512sums="7a15e4c0ae587db4987d673a790a4f3bea1cab29ce24a506fb21fa7bd2f60bfec70867eaa1c1395cb5b0e0ae81a024fb6109b064da0ef50e7c146d2198871c70  collectd-5.12.0.tar.bz2
 a286c2164af196154d017658d6e5aa3cc4f76dadf90b68c3021418979d9f0377776bb990d737ae5c916c04475725365aea8b78e3bc5e2f3679d5a99f8b9af13e  collectd.initd
 3078e43fc1aa5e5d5f7042472f465cc3b077c59f43a9867ade038e59bb210f26f53bb9a1e1e8a198ca53939a4b2e03a1f05628aa54f826746f970faa36acff6a  gnu_source.patch"
